msn_api:
 -  market: india
    site:  http://tvintl.msn.com
    get:
     url: '/DiscoveryWS/GetGridData.ashx'
     params:
      channels: all
      format: xml
      mkt: hi-in
      timezoneOffset: 330
    search:
     url:  DiscoveryWS/ExactSearch2.ashx
     params:
      source: tv
      timezoneOffset: 330
      mkt: hi-in
      observesDST: false

